### ISSUE TITLE
Logo update and suggested landing page

### ISSUE THREAD

**Issue by kernkatja** [Correlate-AS/customer-insights#29]
1. Noticed that when user creates an account in Correlate, he gets email where the old logo is used. 
2. When user clicks on the Add integrations, he gets to the home page - I would suggest that we already open the pop-up. 

![Screenshot 2021-12-06 at 13 36 23](https://user-images.githubusercontent.com/82147817/144847841-fdc8c5f3-88fa-4fd9-8b9e-d4abe0295ddf.png)

https://user-images.githubusercontent.com/82147817/144847809-d6a8901a-155e-4c1b-b44b-8261ad9580cb.mov

Proposed solution for landing page (with open pop-up):

![Screenshot 2021-12-06 at 13 53 04](https://user-images.githubusercontent.com/82147817/144849457-f3aec2e2-0133-406c-ba12-47971414d6e8.png)

**Comment by jedelizabella** [comment]
Thanks for noticing this Katja! I think it is worth thinking about what we want this page to look like. Since we are not only about integrations but also collaboration, boards and teams I think it might also be worth looking into how we want to display the text (which features we want to highlight etc - @PriscilaSelmo  @megan-funesse  maybe something for the marketing team to look into?). I also agree that either we need to update the clickable text in the email or give the users direct access to the integration page in Correlate as shown here :)

**Comment by ghost** [comment]
Hi @kernkatja thanks for flagging this and bringing to our attention. When we're moved over to Hubspot for email automations and CMS we'll be able to clean all this up much easier/quicker. 

For now, 
1. we can update the image in the email with the new logo.
2. either see if dev team can provide that link that directs users directly to that integrations pop up (is this something they can provide?) IF NOT, we can clean up the text in the email not to CTA this action and hold off until the new year to have more fun with CTAs and engaging users in automated email workflows.

@PriscilaSelmo can you update this image in point 1 - It's this link on sendgrid, but I can easily add in on your behalf https://mc.sendgrid.com/dynamic-templates/d-cebdb7b4cc2d4caab3bccd259828546a/version/1d435119-9707-4568-9d97-a0c6eacb7f4d/editor
@kernkatja find out what you can for point 2 and we take it from there.

Thanks!

**Comment by LiubovSmorhonska** [comment]
Hi @megan-funesse @jedelizabella 
1) we will change the logo, ticket is already done :)
2) we have discussed this issue, we can provide possibility for users go directly to integrations pop up. Or we can change text of the button to "Go to Correlate" and send users to home page. Let me know what is more appropriate

**Comment by ghost** [comment]
Thanks @LiubovSmorhonska . 

Sitting on it, as this is their welcome email to go to Correlate I cleaned the text up and deleted the last sentence. I also changed the CTA to just **Login and get started.**

BUT NOW ... I see the link says {integration link} so is this already in effect? Can you revert this to instead go back to the normal login page? I ask because we need to keep it simple for now. If we drive people to start with integrations first and foremost with out showing them a board it's confusing. I think it's a good idea, but we don't even have any product walk throughs to let the user understand how to use these integrations best in the board. Rather for now just take them to the main login. 

Westill need to update the image in the email as it has the old logo on the cardboardbox with all the files. @PriscilaSelmo and I will take care of updating the image.

**Comment by ghost** [comment]
@PriscilaSelmo never mind - nothing for you to create. I realized I had that banner from the crisis comms email so I just used that instead. Images are in and set.

**Comment by LiubovSmorhonska** [comment]
> BUT NOW ... I see the link says {integration link} so is this already in effect? 

No, it was like this, but for some reason pop up was not open and we saw just home page

I got you, we will redirect it to login page.

But as I understood we can get this email only in case when we already logged in in Correlate?

**Comment by ghost** [comment]
Thanks for the clarification @LiubovSmorhonska . It sounds like Igor and I talked it out yesterday. I'm not too worried about the flow for this short term between holidays and getting Hubspot set up in early Jan. As long as the button takes them to Correlate - not a pop of for integrations that doesn't work (yet). We'll move all our automations to that software and marketing can have more of a hold on the content (with your dev help on necessary links). More to discuss in 2022!
